name: "Build"

on:
  workflow_dispatch:
#  release:
#    types: [published]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: "Package Application"
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .

      - name: "Debug"
        run: |
          ls -R dist

      - name: "Upload to Actions"
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: dist/windows

      - name: "Upload to Release"
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: web-ext-artifacts/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
