name: "Build"

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  windows:
    name: "Windows"
    runs-on: windows-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: "PyInstaller"
        run: |
          python -m pip install pyinstaller
          pyinstaller --noconfirm client.spec
          python manifest.py

      - name: "Inno Setup"
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: client.iss
          options: "/DMyAppVersion=${{ github.ref_name }}"

      - name: "Debug"
        run: |
          ls -R out

      - name: "Upload to Actions"
        uses: actions/upload-artifact@v4
        with:
          name: install-win
          path: out

      - name: "Upload to Release"
        uses: svenstaro/upload-release-action@v2
        if: ${{ github.event_name == 'release' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: out/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: "VirusTotal Scan"
        uses: crazy-max/ghaction-virustotal@v4
        if: ${{ github.event_name == 'release' }}
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          update_release_body: true
          files: |
            out/*

  linux:
    name: "Linux"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: "Debian Package"
        run: |
          python manifest.py
          bash build-linux.sh

      - name: "Debug"
        run: |
          ls -R

      - name: "Upload to Actions"
        uses: actions/upload-artifact@v4
        with:
          name: install-linux
          path: out

      - name: "Upload to Release"
        uses: svenstaro/upload-release-action@v2
        if: ${{ github.event_name == 'release' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: out/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: "VirusTotal Scan"
        uses: crazy-max/ghaction-virustotal@v4
        if: ${{ github.event_name == 'release' }}
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          update_release_body: true
          files: |
            out/*

  macos:
    name: "macOS"
    runs-on: macos-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: "Setup Packages"
        run: |
          curl http://s.sudre.free.fr/Software/files/Packages.dmg -o Packages.dmg
          hdiutil attach Packages.dmg
          sudo installer -pkg "/Volumes/Packages 1.2.10/Install Packages.pkg" -target /
          hdiutil detach "/Volumes/Packages 1.2.10"

      - name: "PyInstaller"
        run: |
          python -m pip install pyinstaller
          pyinstaller --noconfirm client.spec
          python manifest.py
          bash build-mac.sh

      - name: "Debug"
        run: |
          ls -R

      - name: "Upload to Actions"
        uses: actions/upload-artifact@v4
        with:
          name: install-macos
          path: out

      - name: "Upload to Release"
        uses: svenstaro/upload-release-action@v2
        if: ${{ github.event_name == 'release' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: out/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: "VirusTotal Scan"
        uses: crazy-max/ghaction-virustotal@v4
        if: ${{ github.event_name == 'release' }}
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          update_release_body: true
          files: |
            out/*
