name: "Build"

on:
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: "Debug"
        run: |
          pip install -r requirements.txt pyinstaller
          pyinstaller --clean --console --onefile py-native-msg.spec

      - name: "Upload to Actions"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: dist
