name: "Build"

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: "Build"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: "Build"
        run: |
          python -m pip install pyinstaller
          pyinstaller py-native-msg.spec

      - name: "Debug"
        run: |
          ls -R dist

      - name: "Upload to Actions"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: dist

  windows:
    name: "Windows"
    runs-on: windows-latest
    timeout-minutes: 5
    needs: build

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Download Artifact"
        uses: actions/download-artifact@v4
        with:
          name: windows-latest
          path: dist

      - name: "Debug 1"
        run: |
          ls -R

      - name: "Inno Setup"
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: install-win.iss

      - name: "Debug 2"
        run: |
          ls -R out

      - name: "Upload to Actions"
        uses: actions/upload-artifact@v4
        with:
          name: install-win
          path: out

      - name: "Upload to Release"
        uses: svenstaro/upload-release-action@v2
        if: ${{ github.event_name == 'release' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: out/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
